### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by 112bzo** [pagermon/pagermon#242]
What I would like to see is a multi-user login. So that more users can be created and that they can log in as a reader and not as an administrator.

If the page is secured, you must log in by name but only have read rights.

Is that possible?

**Comment by davidmckenzie** [comment]
Definitely possible, but definitely far future backlog type stuff. Has been something in the back of my mind since I first made the project - would like to have some kind of user management to allow end users to subscribe to pager messages via email or something. Managing users creates a huge layer of complexity and security though, so it'll probably remain in the backlog for some time.
