### ISSUE TITLE
Large database is incredibly slow to load

### ISSUE THREAD

**Issue by WizRd0** [pagermon/pagermon#592]
**Describe the bug**
My current database has a little over 2 million messages in it.  When accessing the server the pagermon logging shows over a 20 second load time.

> pagermon  | init: 287.639ms
> pagermon  | sql: 20822.587ms
> pagermon  | send: 0.701ms

I have deleted data down to 1000 messages and loading is back down to a usable duration

> pagermon  | init: 42.496ms
> pagermon  | sql: 40.756ms
> pagermon  | send: 0.588ms

**To Reproduce**
Have sufficient enough messages in a MySQL database (I had 2m+)

**Expected behaviour**
I expect that loading the main server page only the count to allow pages to be created and initial page count of messages would be pulled from the database, this should be microseconds, not seconds.

> MariaDB> select count(\*) from messages;
> +----------+
> | count(*) |
> +----------+
> |  2058851 |
> +----------+
> 1 row in set (0.229 sec)
> MariaDB> select * from messages LIMIT 20;
> <omit output>
> 20 rows in set (0.000 sec)

**Environment information:**
 - OS: Ubuntu 22.04
 - Docker Compose Version 2.24.5
 - Database: MariaDB 10.11-3 running on Debian 11 (Remote Host)

**Additional context**
I'm assuming this issue is related to line 115 in server/routes/api.js

> .select('messages.*', 'capcodes.alias', 'capcodes.agency', 'capcodes.icon', 'capcodes.color', 'capcodes.ignore', db.raw('CASE WHEN NOT capcodes.address = messages.address THEN 1 ELSE 0 END as wildcard'))

As there is no limit or offset associated with the query it's trying to pull every message on page loads?

If it helps I have a dump of the database prior to deleting any messages older than 1000.  It's only 270Mb so I can make this available  for troubleshooting / testing.  I will start trying to figure out how to modify api.js but TBH it's just going to be trial and error.

**Comment by DanrwAU** [comment]
My server with 10million messages in the database loads quicker than your server with 1000.....

Are you sure this isn't a resourcing issue with your configuration?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: WizRd0 ***@***.***>
Sent: Monday, March 4, 2024 5:41:10 pm
To: pagermon/pagermon ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pagermon/pagermon] Large database is incredibly slow to load (Issue #592)


Describe the bug
My current database has a little over 2 million messages in it. When accessing the server the pagermon logging shows over a 20 second load time.
pagermon | init: 287.639ms pagermon | sql: 20822.587ms pagermon | send: 0.701ms

I have deleted data down to 1000 messages and loading is back down to a usable duration
pagermon | init: 42.496ms pagermon | sql: 40.756ms pagermon | send: 0.588ms

To Reproduce
Have sufficient enough messages in a MySQL database (I had 2m+)

Expected behaviour
I expect that loading the main server page only the count to allow pages to be created and initial page count of messages would be pulled from the database, this should be microseconds, not seconds.
`> select count() from messages;
+----------+
| count() |
+----------+
| 2058851 |
+----------+
1 row in set (0.229 sec)

select * from messages LIMIT 20;

20 rows in set (0.000 sec) `

Environment information:

  *   OS: Ubuntu 22.04
  *   Docker Compose Version 2.24.5
  *   Database: MariaDB 10.11-3 running on Debian 11 (Remote Host)

Additional context
I'm assuming this issue is related to line 115 in server/routes/api.js
.select('messages.*', 'capcodes.alias', 'capcodes.agency', 'capcodes.icon', 'capcodes.color', 'capcodes.ignore', db.raw('CASE WHEN NOT capcodes.address = messages.address THEN 1 ELSE 0 END as wildcard'))
As there is no limit or offset associated with the query it's trying to pull every message on page loads?

If it helps I have a dump of the database prior to deleting any messages older than 1000. It's only 270Mb so I can make this available for troubleshooting / testing. I will start trying to figure out how to modify api.js but TBH it's just going to be trial and error.
